# 使用说明 V4.4.0
# 1. 使用docker-compose  宿主机不需要配置host来发现
# 2. 无需修改源码，根目录  docker-compose up 即可
# 3. 静静等待服务启动

version: '3'
services:
  elasticsearch:
    image: elasticsearch:7.17.6
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      # 设置集群名称
      cluster.name: elasticsearch
      # 以单一节点模式启动
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    volumes:
      - /docker/elk/elasticsearch/plugins:/usr/share/elasticsearch/plugins
      - /docker/elk/elasticsearch/data:/usr/share/elasticsearch/data
      - /docker/elk/elasticsearch/logs:/usr/share/elasticsearch/logs
    network_mode: "host"

  sky-oap:
    image: apache/skywalking-oap-server:9.3.0
    container_name: sky-oap
    ports:
      - "11800:11800"
      - "12800:12800"
    environment:
      JAVA_OPTS: -Xms1G -Xmx2G
      #记录数据的有效期，单位天
      SW_CORE_RECORD_DATA_TTL: 7
      #分析指标数据的有效期，单位天
      SW_CORE_METRICS_DATA_TTL: 7
      SW_STORAGE: elasticsearch
      SW_STORAGE_ES_CLUSTER_NODES: 127.0.0.1:9200
      TZ: Asia/Shanghai
    network_mode: "host"

  sky-ui:
    image: apache/skywalking-ui:9.3.0
    container_name: sky-ui
    ports:
      - "18080:18080"
    environment:
      SW_SERVER_PORT: 18080
      SW_OAP_ADDRESS: http://127.0.0.1:12800
      TZ: Asia/Shanghai
    depends_on:
      - sky-oap
    network_mode: "host"


  nonpay-rabbitmq:
    image: nonpay-rabbitmq
    container_name: nonpay-rabbitmq
    # 使用 Dockerfile 构建
    build:
      context: /docker/rabbitmq
      dockerfile: Dockerfile
    environment:
      # 控制台账号密码
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"   # api 端口
      - "15672:15672"
    volumes:
      - /docker/rabbitmq/log:/var/log/rabbitmq
      - /docker/rabbitmq/data:/var/lib/rabbitmq
    network_mode: "host"

  nonpay-mysql:
    image: mysql:8.0.31
    container_name: nonpay-mysql
    environment:
      # 时区上海
      TZ: Asia/Shanghai
      # root 密码
      MYSQL_ROOT_PASSWORD: ruoyi123
      # 初始化数据库
      MYSQL_DATABASE: ry-cloud
    ports:
      - "3306:3306"
    volumes:
      # 数据挂载
      - /docker/mysql/data/:/var/lib/mysql/
      # 配置挂载
      - /docker/mysql/conf/:/etc/mysql/conf.d/
    command:
      # 将mysql8.0默认密码策略 修改为 原先 策略 (mysql8.0对其默认策略做了更改 会导致密码无法匹配)
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
    privileged: true
    network_mode: "host"

  nonpay-redis:
    image: redis:6.2.7
    container_name: nonpay-redis
    ports:
      - "6379:6379"
    environment:
      # 时区上海
      TZ: Asia/Shanghai
    volumes:
      # 配置文件
      - /docker/redis/conf:/redis/config
      # 数据文件
      - /docker/redis/data/:/redis/data/
    command: "redis-server /redis/config/redis.conf"
    privileged: true
    network_mode: "host"

  nonpay-nacos:
    build:
      context: ./ruoyi-visual/ruoyi-nacos
    container_name: nonpay-gateway
    image: nonpay-gateway
    ports:
      - "8848:8848"
    network_mode: "host"

  nonpay-gateway:
    build:
      context: ./ruoyi-gateway
    container_name: nonpay-gateway
    image: nonpay-gateway
    ports:
      - "8080:8080"
    volumes:
      # 配置文件
      - /docker/ruoyi-gateway/logs/:/ruoyi/gateway/logs
      # skywalking 探针
      - /docker/skywalking/agent/:/ruoyi/skywalking/agent
    network_mode: "host"

  nonpay-auth:
    build:
      context: ./ruoyi-auth
    container_name: nonpay-auth
    image: nonpay-auth
    ports:
      - "9210:9210"
    volumes:
      # 配置文件
      - /docker/ruoyi-auth/logs/:/ruoyi/auth/logs
      # skywalking 探针
      - /docker/skywalking/agent/:/ruoyi/skywalking/agent
    network_mode: "host"

  nonpay-boss:
    build:
      context: ./ruoyi-modules/ruoyi-boss
    container_name: nonpay-boss
    image: nonpay-boss
    ports:
      - "9206:9206"
    volumes:
      # 配置文件
      - /docker/ruoyi-boss/logs/:/ruoyi/boss/logs
      # skywalking 探针
      - /docker/skywalking/agent/:/ruoyi/skywalking/agent
    network_mode: "host"

  nonpay-mq:
    build:
      context: ./ruoyi-modules/ruoyi-mq
    container_name: nonpay-mq
    image: nonpay-mq
    ports:
      - "9402:9402"
    volumes:
      # 配置文件
      - /docker/ruoyi-mq/logs/:/ruoyi/mq/logs
      # skywalking 探针
      - /docker/skywalking/agent/:/ruoyi/skywalking/agent
    network_mode: "host"

  nonpay-order:
    build:
      context: ./ruoyi-modules/ruoyi-order
    container_name: nonpay-order
    image: nonpay-order
    ports:
      - "9207:9207"
    volumes:
      # 配置文件
      - /docker/ruoyi-order/logs/:/ruoyi/order/logs
      # skywalking 探针
      - /docker/skywalking/agent/:/ruoyi/skywalking/agent
    network_mode: "host"

  nonpay-payment:
    build:
      context: ./ruoyi-modules/ruoyi-payment
    container_name: nonpay-payment
    image: nonpay-payment
    ports:
      - "9209:9209"
    volumes:
      # 配置文件
      - /docker/ruoyi-payment/logs/:/ruoyi/payment/logs
      # skywalking 探针
      - /docker/skywalking/agent/:/ruoyi/skywalking/agent
    network_mode: "host"

  nonpay-resource:
    build:
      context: ./ruoyi-modules/ruoyi-resource
    container_name: nonpay-resource
    image: nonpay-resource
    ports:
      - "9204:9204"
    volumes:
      # 配置文件
      - /docker/ruoyi-resource/logs/:/ruoyi/resource/logs
      # skywalking 探针
      - /docker/skywalking/agent/:/ruoyi/skywalking/agent
    network_mode: "host"

  nonpay-system:
    build:
      context: ./ruoyi-modules/ruoyi-system
    container_name: nonpay-system
    image: nonpay-system
    ports:
      - "9201:9201"
    volumes:
      # 配置文件
      - /docker/ruoyi-system/logs/:/ruoyi/system/logs
      # skywalking 探针
      - /docker/skywalking/agent/:/ruoyi/skywalking/agent
    network_mode: "host"

  nonpay-telegram:
    build:
      context: ./ruoyi-modules/ruoyi-telegram
    container_name: nonpay-telegram
    image: nonpay-telegram
    ports:
      - "9210:9210"
    network_mode: "host"


